"""End-to-end answer loop: govern -> compress -> ask the LLM -> return answer.

This closes the loop: instead of just returning a compressed prompt for a human
to paste into an LLM, it sends the compressed prompt to the LLM itself and
returns the generated answer, plus how many input tokens the compression saved
on that call.

Requires OPENAI_API_KEY (the answer is generated by the model).
"""

from __future__ import annotations

import os

from core.intelligence import count_tokens
from core.pipeline import process


def answer(
    prompt: str,
    target_ratio: float = 0.5,
    target_model: str = "gpt-4o-mini",
    adaptive: bool = False,
    enforce: bool = True,
    max_tokens: int = 800,
) -> dict:
    """Compress `prompt`, send the compressed version to the LLM, return the
    answer plus the token savings on that call.

    Args:
        target_ratio: fraction of tokens to keep when compressing.
        target_model: the model that will answer.
        adaptive: use adaptive (heuristic->LLM) compression instead of heuristic.
        enforce: if a governance verdict is "block", return blocked without
            calling the model.
    """
    # 1) Govern + compress (reuses the full pipeline).
    result = process(prompt, target_ratio=target_ratio, target_model=target_model,
                     adaptive=adaptive, enforce=enforce, use_cache=True)

    if result.get("blocked"):
        return {
            "blocked": True,
            "verdict": result.get("verdict"),
            "reasons": result.get("reasons", []),
            "governance": result.get("governance"),
            "answer": None,
        }

    compressed = result["compressed_text"]
    original_tokens = result.get("original_tokens", count_tokens(prompt))
    compressed_tokens = result.get("compressed_tokens", count_tokens(compressed))

    if not os.getenv("OPENAI_API_KEY"):
        return {
            "blocked": False,
            "answer": None,
            "error": "OPENAI_API_KEY not set on the server — cannot generate an answer.",
            "compressed_prompt": compressed,
            "governance": result.get("governance"),
        }

    # 2) Send the COMPRESSED prompt to the LLM and get the answer.
    from openai import OpenAI

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    resp = client.chat.completions.create(
        model=target_model,
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": compressed}],
    )
    answer_text = (resp.choices[0].message.content or "").strip()
    usage = getattr(resp, "usage", None)

    # 3) Return the answer + what the compression saved on this call.
    return {
        "blocked": False,
        "verdict": result.get("verdict"),
        "governance": result.get("governance"),
        "original_prompt": prompt,
        "compressed_prompt": compressed,
        "answer": answer_text,
        "model": target_model,
        "prompt_type": (result.get("governance") or {}).get("classification", {}).get("category"),
        "input_tokens_if_original": original_tokens,
        "input_tokens_sent": compressed_tokens,
        "input_tokens_saved": max(0, original_tokens - compressed_tokens),
        "reduction_pct": result.get("reduction_pct"),
        "llm_usage": {
            "prompt_tokens": getattr(usage, "prompt_tokens", None),
            "completion_tokens": getattr(usage, "completion_tokens", None),
            "total_tokens": getattr(usage, "total_tokens", None),
        } if usage else None,
    }
